---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jre
- name: Create orientdb group
  become: true
  become_user: root
  ansible.builtin.group:
    name: '{{ orientdb_group }}'
    state: present

- name: Create orientdb user and home directory
  become: true
  become_user: root
  ansible.builtin.user:
    name: '{{ orientdb_user }}'
    group: '{{ orientdb_group }}'
    home: '{{ orientdb_home }}'
    state: present

- name: Check for install in {{ orientdb_install_dir }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ orientdb_install_dir }}'
  changed_when: false
  register: orientdb_binary

- name: Downloading and installing orientdb
  when: not orientdb_binary.stat.exists
  block:
    - name: Downloading {{ orientdb_tgz_url }} to {{ orientdb_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ orientdb_tgz_url }}'
        dest: '{{ orientdb_tmp_tgz }}'
        owner: '{{ orientdb_user }}'
        group: '{{ orientdb_group }}'
        checksum: '{{ orientdb_checksum }}'
        mode: '644'
    - name: Unarchive {{ orientdb_tmp_tgz }} to {{ orientdb_home }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ orientdb_tmp_tgz }}'
        dest: '{{ orientdb_home }}'
        owner: '{{ orientdb_user }}'
        group: '{{ orientdb_group }}'
        creates: '{{ orientdb_install_dir }}'
  always:
    - name: Rm -f {{ orientdb_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ orientdb_tmp_tgz }}'
        state: absent

- name: Linking {{ orientdb_link_dir }} to {{ orientdb_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    state: link
    src: '{{ orientdb_install_dir }}'
    dest: '{{ orientdb_link_dir }}'
    owner: '{{ orientdb_user }}'
    group: '{{ orientdb_group }}'
