---
- name: create orientdb group
  become: yes
  become_user: root
  group: >
    name={{orientdb_group}}
    state=present

- name: create orientdb user
  become: yes
  become_user: root
  user: >-
    name={{orientdb_user}}
    group={{orientdb_group}}
    home={{orientdb_home}}
    state=present

- name: download tgz
  become: yes
  become_user: '{{orientdb_user}}'
  get_url: >-
    url={{orientdb_tgz_url}}
    dest={{orientdb_home}}/{{orientdb_tgz}}
    mode=0644

- name: unarchive
  become: yes
  become_user: orientdb
  unarchive: >-
    copy=no
    src={{orientdb_home}}/{{orientdb_tgz}}
    dest={{orientdb_home}}
    creates={{orientdb_home}}/{{orientdb_name}}

- name: link /opt/orientdb
  become: yes
  become_user: '{{orientdb_user}}'
  file: >-
    state=link
    src={{orientdb_home}}/{{orientdb_name}}
    dest={{orientdb_home}}/orientdb

    
