---
- name: create orientdb group
  become: true
  become_user: root
  group:
    name: '{{ orientdb_group }}'
    state: present

- name: create orientdb user and home directory
  become: true
  become_user: root
  user:
    name: '{{ orientdb_user }}'
    group: '{{ orientdb_group }}'
    home: '{{ orientdb_home }}'
    state: present

- name: check for install in {{ orientdb_install_dir }}
  become: true
  become_user: root
  stat:
    path: '{{ orientdb_install_dir }}'
  changed_when: false
  register: orientdb_binary

- when: not orientdb_binary.stat.exists
  block:
    - name: downloading {{ orientdb_tgz_url }} to {{ orientdb_tmp_tgz }}
      become: true
      become_user: root
      get_url:
        url: '{{ orientdb_tgz_url }}'
        dest: '{{ orientdb_tmp_tgz }}'
        owner: '{{ orientdb_user }}'
        group: '{{ orientdb_group }}'
        checksum: '{{ orientdb_checksum }}'
        mode: '0644'
    - name: unarchive {{ orient_tmp_tgz }} to {{ orientdb_home }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ orientdb_tmp_tgz }}'
        dest: '{{ orientdb_home }}'
        owner: '{{ orientdb_user }}'
        group: '{{ orientdb_group }}'
        creates: '{{ orientdb_install_dir }}'
  always:
    - name: rm {{ orientdb_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ orientdb_tmp_tgz }}'
        state: absent

- name: linking {{ orientdb_link_dir }} to {{ orientdb_install_dir }}
  become: true
  become_user: root
  file:
    state: link
    src: '{{ orientdb_install_dir }}'
    dest: '{{ orientdb_link_dir }}'
    owner: '{{ orientdb_user }}'
    group: '{{ orientdb_group }}'
